# Generated by Django 5.0.3 on 2024-05-18 14:40

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('management', '0002_alter_doctoravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='days_of_week',
            field=management.models.DaysOfWeekField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=13, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'days_of_week', 'day_of_month', 'start_time', 'end_time', 'year', 'month', 'recurring_monthly')},
        ),
    ]
