# Generated by Django 5.0.3 on 2024-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_doctoravailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
