# Generated by Django 5.0.3 on 2024-06-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Products Categories'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Products Images'},
        ),
    ]
