# Generated by Django 5.0.3 on 2024-05-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_image_revenue_drug_category_alter_drug_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=3000, upload_to='drug_images/'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='pharmacy.consultationcategory'),
        ),
    ]
